### PR TITLE
Add considerations for STOP\_SENDING

### PR DESCRIPTION
**Pull request by mengelbart**

### CODE REVIEW

**Comment by mengelbart** [comment]
closes #45

**Review by SpencerDawkins — COMMENTED** [review]
Thank you for working through the comments about this. 

I think (but could be wrong) that we are complicating our work by saying "this is how ROQ works", and then having to clarify that "this is a QUIC streams thing (like STOP\_SENDING), and the rules are different if you're using QUIC datagrams (as below), and (of course) it's legal for ROQ endpoints to use both". 

But that's a question for another issue. On **this issue** ... 

> QUIC allows an application to abort reading the stream and specify an error code
> {{Section 3.5 of !RFC9000}}. The QUIC transport can signal this to the sending
> side by sending a STOP\_SENDING frame. The sender SHOULD not interpret the
> reception of STOP\_SENDING as an indication that the receiver lost interest in
> the media stream as a whole, but rather that a part of the media stream was not
> received timely and some recovery is necessary. 

Hmmm. Is this a normative requirement on QUIC, beyond RFC 9000/RFC 9221? I think we might express this better as 

The **sending RTP application** SHOULD not interpret the reception of STOP\_SENDING as an indication that the receiver lost interest in the media stream as a whole, but rather that a part of the media stream was not received timely and some recovery **is probably** necessary.

> The recovery may be supported by
> dropping some parts of the media stream entirely and restarting to send new
> media frames on new QUIC streams. While STOP\_SENDING includes an error code, it
> does not allow the receiving side to inform the sender where exactly it wishes
> to restart receiving media. A sender that receives STOP\_SENDING MUST NOT
> transmit any frames already sent on the QUIC stream, on which STOP\_SENDING was
> received, on a new QUIC stream. 

I was confused here. Is this saying the (sending RTP application) MUST NOT retransmit **media** frames on the new stream, or MUST NOT retransmit QUIC frames on the new stream?

> A sender SHOULD instead continue to send media
> frames on new QUIC streams starting with the first frame that was not
> transmitted on the stream that received STOP\_SENDING.

Skipping down to 

> **Editor's note:** A receiver cannot cancel a certain frame but still receive
> retransmissions for a frame the was following on the same stream using
> STOP\_SENDING, because STOP\_SENDING does not include an offset which would
> allow signaling where retransmissions should continue. If this is a required
> feature for RoQ, it could be implemented using an extended STOP\_SENDING frame
> as, for example, proposed in {{?I-D.draft-thomson-quic-enough-00}}

Do we have a complete list of QUIC extension RFCs and drafts we think might be useful in ROQ? That would be a fine thing to add.

**Comment by mengelbart** [comment]
> The sending RTP application SHOULD not interpret the reception of STOP_SENDING as an indication that the receiver lost interest in the media stream as a whole, but rather that a part of the media stream was not received timely and some recovery is probably necessary.

Sounds good. I will change it.

> I was confused here. Is this saying the (sending RTP application) MUST NOT retransmit media frames on the new stream, or MUST NOT retransmit QUIC frames on the new stream?

This should be media frames, I will add it to clarify. 

> Do we have a complete list of QUIC extension RFCs and drafts we think might be useful in ROQ? That would be a fine thing to add.

That is a good idea, I opened #92

**Comment by mengelbart** [comment]
I am not sure I understand your comment here:

> I think (but could be wrong) that we are complicating our work by saying "this is how ROQ works", and then having to clarify that "this is a QUIC streams thing (like STOP_SENDING), and the rules are different if you're using QUIC datagrams (as below), and (of course) it's legal for ROQ endpoints to use both".
> 
> But that's a question for another issue. On this issue ...

Would you mind opening that issue?

**Comment by SpencerDawkins** [comment]
Preferring "RTP sender", rather than "sender".

**Comment by SpencerDawkins** [comment]
> I am not sure I understand your comment here:
> 
>> I think (but could be wrong) that we are complicating our work by saying "this is how ROQ works", and then having to clarify that "this is a QUIC streams thing (like STOP_SENDING), and the rules are different if you're using QUIC datagrams (as below), and (of course) it's legal for ROQ endpoints to use both".
>>
>> But that's a question for another issue. On this issue ...
>
> Would you mind opening that issue?

Let's wait to think about this some more, but I'll open an issue for it when it becomes an issue. :grinning:

**Pull request merged**
